name: flutter_deezer_app
description: Unofficial Deezer client, built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: MabryDeezer
      fonts:
        - asset: assets/fonts/MabryDeezer/MabryDeezer-Black.otf
          weight: 900
        - asset: assets/fonts/MabryDeezer/MabryDeezer-Bold.otf
          weight: 700
        - asset: assets/fonts/MabryDeezer/MabryDeezer-Light.otf
          weight: 300
        - asset: assets/fonts/MabryDeezer/MabryDeezer-Medium.otf
          weight: 500
        - asset: assets/fonts/MabryDeezer/MabryDeezer-Regular.otf
          weight: 400
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic/NotoSansArabic-Medium.ttf
          weight: 500
    - family: NotoSansHebrew
      fonts:
        - asset: assets/fonts/NotoSansHebrew/NotoSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansHebrew/NotoSansHebrew-Medium.ttf
          weight: 500
  generate: true
  uses-material-design: true
